### ISSUE TITLE
rc.auditd should have execute permissions by default

### ISSUE THREAD

**Issue by bobbintb** [conraid/SlackBuilds#33]
When auditd installs, the rc.auditd script does not have execute permissions. The permission must be added before auditd can be used. It should have 755 permissions.

**Comment by conraid** [comment]
I will check as soon as I can. Thank you for the notice.

**Comment by bobbintb** [comment]
Thank you for saving me a ton of time making my own builds.

**Comment by conraid** [comment]
For the package from version 4.0.2 I put the permissions to 755, however, consider that doinst.sh, when it goes to handle rc.auditd.new, will set the permissions based on how they were before, if the rc.auditd file already exists, so you have to delete the file if you want to see the correctness of the package installed the first time.
Since version 4 they have changed the init procedure a bit, I took the old script, let me know if there are any problems though. Thank you.

p.s.
I don't know when I'll be able to commit, I have to recompile all the software that depends on boost and I have an old pc and it's too hot to keep it on too much :/
