### ISSUE TITLE
neomutt in Sbo

### ISSUE THREAD

**Issue by Tonus1** [conraid/SlackBuilds#8]
Hi,
I was wondering why your slackbuild was not in Sbo ?

Must admit I used yours with very few modifications to build my package (build with slang).

Only one problem, had to disable lua since it wouldn't compile with Sbo package installed.

**Comment by conraid** [comment]
Because I only use the current and I have no way of trying on stable at the moment. 
Also I have to change some things in my scripts to adapt to their template, even if I try as much as possible to comply with them (such as permissions, users, etc ...).
As soon as the stable comes out I'll try to send some SlackBuilds.

Thanks and sorry for the delay, but I don't get the notifications: /
And I'm sorry for my bad english :)
